server:
  host: 0.0.0.0
  port: 8005
model:
  repo_id: KittenML/kitten-tts-nano-0.8-fp32
tts_engine:
  device: auto
paths:
  model_cache: model_cache
generation_defaults:
  speed: 1.0
  language: en
audio_output:
  format: wav
  sample_rate: 24000
ui_state:
  last_text: ''
  last_voice: Jasper
  last_chunk_size: 120
  last_split_text_enabled: true
  hide_chunk_warning: false
  hide_generation_warning: false
  theme: dark
ui:
  title: Kitten TTS Server
  show_language_select: true
debug:
  save_intermediate_audio: false
